version: "3.7"

services:
  react-app:
    container_name: reactApp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 512M